config/routes.rb
Rails.application.routes.draw do

  root to: "home#top"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  resources :users, only: [:show, :edit, :update] do
    member do
      get :profile
    end
  end

  resources :rooms do
    collection do
      get :own
    end
  end

  resources :reservations, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :rooms, :dependent => :destroy
  has_many :reservations, :dependent => :destroy

  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit params.require(:user).permit(:name, :email, :password, :password_confirmation
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    root_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_user_registration_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :profile, :edit, :update]
  before_action :ensure_correct_user, only: [:show, :profile, :edit, :update]

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集が正常に完了しました"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :avatar)
    end

    def ensure_correct_user
      if current_user.id != params[:id].to_i
        flash[:notice] = "権限がありません"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<section class="show-section">
  <h2 class="show-page-title">設定</h2>
  <div class="show-container">
    <ul class="side-nav">
      <li class="side-nav-item"><%= link_to "アカウント", user_path(@user) %></li>
      <li class="side-nav-item"><%= link_to "プロフィール", profile_user_path(@user) %></li>
    </ul>
    <div class="account-info">
      <div class="account-info-header">
        <h3>プロフィール</h3>
        <%= link_to "編集", edit_user_path(@user), class: "button account-info-link" %>
      </div>
      <%= form_with model: @user, local: true do |f| %>
        <%= render "shared/error_messages" %>

        <div class="account-info-item">
          <label class="account-info-label">アイコン画像</label>
          <%= f.file_field :avatar, class: "account-info-value file-input" %>
        </div>
        <div class="account-info-item">
          <label class="account-info-label">名前</label>
          <%= f.text_field :name, class: "account-info-value string-input", value: "#{@user.name}" %>
        </div>
        <div class="account-info-item">
          <label class="account-info-label">自己紹介</label>
          <%= f.text_area :introduction, class: "account-info-value introduction-input", value: "#{@user.introduction}" %>
        </div>
        <div class="button-area">
          <%= link_to "キャンセル", profile_user_path(@user), class: "button cancel-button" %>
          <%= f.submit "保存", class: "button submit-button" %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/profile.html.erb
<section class="show-section">
  <h2 class="show-page-title">設定</h2>
  <div class="show-container">
    <ul class="side-nav">
      <li class="side-nav-item"><%= link_to "アカウント", user_path(@user) %></li>
      <li class="side-nav-item"><%= link_to "プロフィール", profile_user_path(@user) %></li>
    </ul>
    <div class="account-info">
      <div class="account-info-header">
        <h3>プロフィール</h3>
        <%= link_to "編集", edit_user_path(@user), class: "button account-info-link" %>
      </div>
      <div class="account-info-item">
        <label class="account-info-label">アイコン画像</label>
        <p class="account-info-value">
          <% if @user.avatar.present? %>
            <%= image_tag @user.avatar.variant(resize: '80x80') %>
          <% else %>
            <%= image_tag "default.png", size: "80x80" %>
          <% end %>
        </p>
      </div>
      <div class="account-info-item">
        <label class="account-info-label">名前</label>
        <p class="account-info-value"><%= @user.name %></p>
      </div>
      <div class="account-info-item">
        <label class="account-info-label">自己紹介</label>
        <p class="account-info-value"><%= @user.introduction %></p>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="show-section">
  <h2 class="show-page-title">設定</h2>
  <div class="show-container">
    <ul class="side-nav">
      <li class="side-nav-item"><%= link_to "アカウント", user_path(@user) %></li>
      <li class="side-nav-item"><%= link_to "プロフィール", profile_user_path(@user) %></li>
    </ul>
    <div class="account-info">
      <div class="account-info-header">
        <h3>アカウント</h3>
        <%= link_to "編集", edit_user_registration_path(@user), class: "button account-info-link" %>
      </div>
      <div class="account-info-item">
        <label class="account-info-label">メールアドレス</label>
        <p class="account-info-value"><%= @user.email %></p>
      </div>
      <div class="account-info-item">
        <label class="account-info-label">パスワード</label>
        <p class="account-info-value">＊＊＊＊＊＊＊＊</p>
      </div>
    </div>
  </div>
</section>