config/routes.rb
Rails.application.routes.draw do

  root to: "home#top"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  resources :users, only: [:show, :edit, :update] do
    member do
      get :profile
    end
  end

  resources :rooms do
    collection do
      get :own
    end
  end

  resources :reservations, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :num_of_people, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
  validate :end_date_check

  belongs_to :user
  belongs_to :room

  def end_date_check
    return if (start_date.nil? || end_date.nil?)
    errors.add(:end_date, "は開始日より前の日付は選択出来ません") if start_date > end_date
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :confirm, :create, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :confirm, :create, :edit, :update, :destroy]

  def index
    @reservations = @user.reservations
  end

  def confirm
    if request.post?
      @reservation =  Reservation.new
      @reservation.assign_attributes(reservation_params)
      if @reservation.invalid?
        @room = Room.find(@reservation.room_id)
        render "rooms/show"
      end
    elsif request.patch?
      @reservation = Reservation.find(params[:id])
      @reservation.assign_attributes(reservation_params)
      if @reservation.invalid?
        render "edit"
      end
    end
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.save
    flash[:notice] = "予約が完了しました"
    redirect_to reservations_path
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(reservation_params)
    flash[:notice] = "予約変更が正常に完了しました"
    redirect_to reservations_path
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    flash[:notice] = "予約を削除しました"
    redirect_to reservations_path
  end

  private
    def reservation_params
      params.require(:reservation).permit(:user_id, :room_id, :start_date, :end_date, :num_of_people)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/confirm.html.erb
<div class="form-wrapper">
  <section class="form-container">
    <h2>予約内容の確認</h2>
    <%= form_with model: @reservation do |f| %>
      <div class="reservation-confirm">
        <div class="reservation-confirm-item">
          <p class="reservation-confirm-label">チェックイン</p>
          <p class="reservation-confirm-value"><%= l @reservation.start_date %></p>
        </div>
        <div class="reservation-confirm-item">
          <p class="reservation-confirm-label">チェックアウト</p>
          <p class="reservation-confirm-value"><%= l @reservation.end_date %></p>
        </div>
        <div class="reservation-confirm-item">
          <p class="reservation-confirm-label">日数</p>
          <p class="reservation-confirm-value"><%= (@reservation.end_date - @reservation.start_date).to_i %>日</p>
        </div>
        <div class="reservation-confirm-item">
          <p class="reservation-confirm-label">人数</p>
          <p class="reservation-confirm-value"><%= @reservation.num_of_people %>人</p>
        </div>
        <div class="reservation-confirm-item">
          <p class="reservation-confirm-label">お支払い金額</p>
          <p class="reservation-confirm-value"><%= @reservation.room.price * @reservation.num_of_people * (@reservation.end_date - @reservation.start_date).to_i %>円</p>
        </div>
        <p class="reservation-confirm-description">上記内容で正しければ「確定」ボタンを押してください。</p>
        <%= f.hidden_field :room_id %>
        <%= f.hidden_field :user_id %>
        <%= f.hidden_field :start_date %>
        <%= f.hidden_field :end_date %>
        <%= f.hidden_field :num_of_people %>
      </div>
      <%= f.submit "予約を確定", class: "button submit-button reservation-submit-button" %>
    <% end %>
    <%= link_to "キャンセル", room_path(@reservation.room), class: "button reservation-cancel-button" %>
  </section>
</div>

app/views/reservations/edit.html.erb
<div class="form-wrapper">
  <section class="form-container">
    <h2>再予約する</h2>
    <%= render "shared/error_messages_reservation" %>
    <div class="reservation-details">
      <% if @reservation.room.avatar.present? %>
        <%= image_tag @reservation.room.avatar, class: "reservation-details-image", alt: "施設画像" %>
      <% else %>
        <%= image_tag "room_default.png",class: "reservation-detail-image", alt: "施設画像" %>
      <% end %>
      <div class="reservation-details-title">
        <p class="reservation-details-room-name"><%= @reservation.room.name %></p>
        <p class="reservation-details-room-price"><%= @reservation.room.price.to_s(:currency) %>~</p>
      </div>
      <p class="reservation-details-room-address"><%= @reservation.room.address %></p>
      <p class="reservation-details-room-introduction"><%= @reservation.room.introduction %></p>
    </div>

    <%= form_with model: @reservation, url: confirm_reservation_path(@reservation) do |f| %>
      <%= render "shared/error_messages_reservation" %>

      <div class="reservation-form">
        <div class="reservation-form-item-edit">
          <%= f.label :start_date, "チェックイン" %>
          <%= f.date_field :start_date %>
        </div>

        <div class="reservation-form-item-edit">
          <%= f.label :end_date, "チェックアウト" %>
          <%= f.date_field :end_date %>
        </div>

        <div class="reservation-form-item-edit">
          <%= f.label :num_of_people, "人数" %>
          <%= f.number_field :num_of_people %>
        </div>

        <%= f.submit "再予約する", class: "button submit-button reservation-submit-button" %>
      </div>
    <% end %>
    <%= link_to "キャンセル", reservations_path, class: "button reservation-cancel-button" %>
  </section>
</div>

app/views/reservations/index.html.erb
<section class="container own-container">
  <h2>登録済み一覧</h2>
  <div class="table-wrapper">
    <table class="table own-table">
      <thead>
        <tr>
          <th>画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th>合計料金</th>
          <th>チェックイン</th>
          <th>チェックアウト</th>
          <th>予約確定日時</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @reservations.each do |r| %>
          <tr>
            <td>
              <% if r.room.avatar.present? %>
                <%= image_tag r.room.avatar.variant(resize: '120x90'), alt: "施設画像" %>
              <% else %>
                <%= image_tag "room_default.png", size: "120x90", alt: "施設画像" %>
              <% end %>
            </td>
            <td><%= link_to r.room.name, room_path(r.room) %></td>
            <td><%= r.room.introduction %></td>
            <td class="nowrap"><%= r.room.price * r.num_of_people * (r.end_date - r.start_date).to_i %>円</td>
            <td class="nowrap"><%= l r.start_date %></td>
            <td class="nowrap"><%= l r.end_date %></td>
            <td><%= l r.created_at, format: :long %></td>
            <td class="nowrap"><%= link_to "再予約", edit_reservation_path(r) %></td>
            <td class="nowrap"><%= link_to "削除", reservation_path(r), method: :delete, data: {confirm: "本当に削除しますか？"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>