config/routes.rb
Rails.application.routes.draw do

  root to: "home#top"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }

  resources :users, only: [:show, :edit, :update] do
    member do
      get :profile
    end
  end

  resources :rooms do
    collection do
      get :own
    end
  end

  resources :reservations, only: [:index, :create, :edit, :update, :destroy] do
    collection do
      post :confirm
    end
    member do
      patch :confirm
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true, length: {maximum: 100}
  validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :address, presence: true

  has_one_attached :avatar
  belongs_to :user
  has_many :reservations, :dependent => :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :own]
  before_action :login_check, only: [:show]
  before_action :set_user, only: [:new, :create, :show, :edit, :update, :destroy, :own]

  def index
    @rooms = Room.where("address like ? and (name like ? or introduction like ?)", "%#{params[:area]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%")
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:notice] = "新しい宿泊施設を登録しました"
      redirect_to rooms_path
    else
      render "new"
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @room = Room.find(params[:id])
    if @user.id == @room.user_id
      @reservation = Reservation.new
    else
      flash[:notice] = "権限がありません"
      redirect_to root_path
    end
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:notice] = "編集が正常に完了しました"
      redirect_to own_room_path(@user)
    else
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    flash[:notice] = "削除が正常に完了しました"
    redirect_to own_rooms_path
  end

  def own
    @rooms = @user.rooms
  end

  private
    def room_params
      params.require(:room).permit(:name, :user_id, :introduction, :price, :address, :avatar)
    end

    def login_check
      if current_user.nil?
        flash[:notice] = "以降の閲覧にはログインが必要です"
        redirect_to new_user_session_path
      end
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="form-wrapper">
  <div class="form-container">
    <h2 class="form-container-title">施設情報の編集</h2>
    <%= form_with model: @room, local: true do |f| %>
      <%= render "shared/error_messages_room" %>

      <div class="account-info-item">
        <%= f.label :name, class: "account-info-label" %>
        <%= f.text_field :name, placeholder: "ルーム名", class: "account-info-value string-input" %>
      </div>

      <div class="account-info-item">
        <%= f.label :introduction, class: "account-info-label" %>
        <%= f.text_area :introduction, placeholder: "施設詳細", class: "account-info-value introduction-input" %>
      </div>

      <div class="account-info-item">
        <%= f.label :price, class: "account-info-label" %>
        <%= f.number_field :price, placeholder: "１日あたりの料金", class: "account-info-value string-input" %>
      </div>

      <div class="account-info-item">
        <%= f.label :address, class: "account-info-label" %>
        <%= f.text_field :address, placeholder: "施設の住所", class: "account-info-value string-input" %>
      </div>

      <div class="account-info-item">
        <label class="account-info-label">施設画像</label>
        <%= f.file_field :avatar, class: "account-info-value file-input" %>
      </div>

      <%= f.hidden_field :user_id, value: @user.id %>

      <div class="button-area">
        <%= link_to "キャンセル", own_rooms_path, class: "button different-button" %></li>
        <%= f.submit "保存", class: "button submit-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<%= render "shared/search" %>

<div class="container room-container">
  <p class="room-result"><%= @rooms.count %>件が見つかりました<p>
  <ul class="room-list">
    <% @rooms.each do |room| %>
      <li class="room">
        <% if room.avatar.present? %>
          <%= image_tag room.avatar, class: "room-image", alt: "施設画像" %>
        <% else %>
          <%= image_tag "room_default.png",class: "room-image", alt: "施設画像" %>
        <% end %>
        <div class="room-body">
          <p class="room-name"><%= room.name %></p>
          <p class="room-address"><%= room.address %></p>
          <p class="room-introduction"><%= room.introduction %></p>
          <div class="room-footer">
            <p class="room-price"><%= room.price.to_s(:currency) %>~</p>
            <%= link_to "詳細はこちら", room_path(room), class: "button room-link-button" %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/rooms/new.html.erb
<div class="form-wrapper">
  <div class="form-container">
    <h2 class="form-container-title">新規登録</h2>
    <%= form_with model: @room do |f| %>
      <%= render "shared/error_messages_room" %>

      <div class="account-info-item">
        <%= f.label :name, class: "account-info-label" %>
        <%= f.text_field :name, placeholder: "ルーム名", class: "account-info-value string-input" %>
      </div>

      <div class="account-info-item">
        <%= f.label :introduction, class: "account-info-label" %>
        <%= f.text_area :introduction, placeholder: "施設詳細", class: "account-info-value introduction-input" %>
      </div>

      <div class="account-info-item">
        <%= f.label :price, class: "account-info-label" %>
        <%= f.number_field :price, placeholder: "１日あたりの料金", class: "account-info-value string-input" %>
      </div>

      <div class="account-info-item">
        <%= f.label :address, class: "account-info-label" %>
        <%= f.text_field :address, placeholder: "施設の住所", class: "account-info-value string-input" %>
      </div>

      <div class="account-info-item">
        <label class="account-info-label">施設画像</label>
        <%= f.file_field :avatar, class: "account-info-value file-input" %>
      </div>

      <%= f.hidden_field :user_id, value: @user.id %>

      <div class="button-area">
        <%= link_to "キャンセル", :back, class: "button different-button" %></li>
        <%= f.submit "保存", class: "button submit-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/own.html.erb
<section class="container own-container">
  <h2>登録済み一覧</h2>
  <div class="table-wrapper">
    <table class="table own-table">
      <thead>
        <tr>
          <th>画像</th>
          <th>施設名</th>
          <th>紹介文</th>
          <th>料金</th>
          <th>作成日</th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td>
              <% if room.avatar.present? %>
                <%= image_tag room.avatar.variant(resize: '120x90'), alt: "施設画像" %>
              <% else %>
                <%= image_tag "room_default.png", size: "120x90", alt: "施設画像" %>
              <% end %>
            </td>
            <td><%= link_to room.name, room_path(room) %></td>
            <td><%= room.introduction %></td>
            <td class="nowrap"><%= room.price.to_s(:currency) %>~</td>
            <td><%= l room.created_at %></td>
            <td class="nowrap"><%= link_to "編集", edit_room_path(room) %></td>
            <td class="nowrap"><%= link_to "削除", room_path(room), method: :delete, data: {confirm: "本当に削除しますか？"} %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/rooms/show.html.erb
<%= render "shared/search" %>

<div class="container room-container">
  <div class="room-header">
    <%= link_to "← 戻る", :back %>
  </div>

  <div class="room-details">
    <% if @room.avatar.present? %>
      <%= image_tag @room.avatar, class: "room-details-image", alt: "施設画像" %>
    <% else %>
      <%= image_tag "room_default.png",class: "room-details-image", alt: "施設画像" %>
    <% end %>

    <div class="room-details-body">
      <%= render "shared/error_messages_reservation" %>

      <div class="room-details-title">
        <p class="room-details-name"><%= @room.name %></p>
        <p class="room-details-price"><%= @room.price.to_s(:currency) %>~</p>
      </div>
      <p class="room-details-address"><%= @room.address %></p>
      <p class="room-details-introduction"><%= @room.introduction %></p>

      <div class="reservation-form">
        <%= form_with model: Reservation.new, url: confirm_reservations_path, method: :post do |f| %>
          <div class="form-input-container">
            <div class="reservation-form-item">
              <%= f.label :start_date, "チェックイン" %>
              <%= f.date_field :start_date %>
            </div>

            <div class="reservation-form-item">
              <%= f.label :end_date, "チェックアウト" %>
              <%= f.date_field :end_date %>
            </div>

            <div class="reservation-form-item">
              <%= f.label :num_of_people, "人数" %>
              <%= f.number_field :num_of_people %>
            </div>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :user_id, value: @user.id %>
          </div>

          <%= f.submit "予約する", class: "button submit-button reservation-submit-button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>